### ISSUE TITLE
issues  of problems  to install 

### ISSUE THREAD

**Issue by sksagor** [ABHIJEET-MUNESHWAR/Ticket-Booking#1]
Dear 
I am Using Win8  And wamp server as my local server  also installed virtual box  for  Linux .
but am confused  how to install Ticket-Booking website in my wamp server using virtual box .
 please guide me as it possible.
sksagor

**Comment by ABHIJEET-MUNESHWAR** [comment]
Hi,

Do you want to set up Ticket-Booking website in Windows or in Virtual box of Linux ?

**Comment by sksagor** [comment]
yaep   plz ... suggest me how can i use that

On Fri, Jan 2, 2015 at 2:17 AM, Abhijeet Ashok Muneshwar <
notifications@github.com> wrote:

> Closed #1 https://github.com/ABHIJEET-MUNESHWAR/Ticket-Booking/issues/1.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ABHIJEET-MUNESHWAR/Ticket-Booking/issues/1#event-213399020
> .

## 

SK Sagor

**Comment by ABHIJEET-MUNESHWAR** [comment]
Hi,

Where do you want to set up Ticket-Booking website? 
In Windows or in Virtual box of Linux ?

**Comment by sksagor** [comment]
virtualb box  linux

On Sun, Jan 11, 2015 at 10:32 AM, Abhijeet Ashok Muneshwar <
notifications@github.com> wrote:

> Hi,
> 
> Where do you want to set up Ticket-Booking website?
> In Windows or in Virtual box of Linux ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ABHIJEET-MUNESHWAR/Ticket-Booking/issues/1#issuecomment-69505044
> .

## 

SK Sagor

**Comment by ABHIJEET-MUNESHWAR** [comment]
Just copy paste entire project in www folder of server & then follow instructions given in
https://github.com/ABHIJEET-MUNESHWAR/Ticket-Booking/blob/master/Readme.txt
